---
- hosts: localhost

  tasks:

    - name: Include var target_hosts from gloabal vars file
      include_vars: '../inventory/group_vars/all.yml'

    - name: Ansible remove words example
      set_fact:
         target_hosts: "{{ target_hosts }}"
  
    - debug:
        var: target_hosts[1]

- hosts:  target_hosts[1]  
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: ubuntu       # Update username for remote server
  vars:
    tomcat_ver: 9.0.30                          # Tomcat version to install
    ui_manager_user: manager                    # User who can access the UI manager section only
    ui_manager_pass: PoshaBiral@2021            # UI manager user password
    ui_admin_username: admin                    # User who can access bpth manager and admin UI sections
    ui_admin_pass: PoshaBiral@2021              # UI admin password
  roles:
    - tomcat

