---
- name: host file update -Local DNS setup across all the servers
  hosts: "localhost"
  connection: local
  become: false
  gather_facts: true  
  ## plugin: amazon.aws.aws_ec2
  #regions: 
  #  - us-east-1
  #  - us-east-2
  #user : user
  #sudo : yes    
  tasks:

    #- name: List several EC2 instances according to their name tag
    #  ec2_instance_info:
    #    region:
    #      - us-east-1
    #      - us-east-2
    #  register: result

  #- name : Copy script
  #  copy : 'src=/home/etc/ansible/ec2.py dest=/opt/root2/logchecker.py owner=root group=root mode=755'
  
  #- name : Execute script
  #  command : '/usr/bin/python /opt/root2/logchecker.py'
  #  - debug:
  #      var: result
    
    - name : Execute script
      command: 'ansible -i /etc/ansible/ec2.py tag_Name_tomcat-node* --list'
      register: result 
    
    - name: splitting stdout to make an ansible list of hosts
      set_fact:
        hostlist: result.stdout.split(',')
    
    - name: make sure packages required are installed on this control node
      pip:
        name:
          - netaddr
      check_mode: true
      when: workshop_type == "networking"
      register: package_stat

    - name: craeting a list of IP Addresses only from the hostlist variable
      set_fact:
        ansible_hostname: "{{ hostlist | ipaddr('address')}}"
        #ansible_hostname: "{{ hostlist | select('match','(/^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)' ) | list }}"

    - debug:
        var: "{{ansible_hostname}}"

    - name: Update the /etc/hosts file with node name
      tags: etchostsupdate
      become: yes
      become_user: "root"
      lineinfile:
        path: "/etc/ansible/hosts"
        regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        state: present
        backup: no
      register: etchostsupdate
      when: ansible_hostname != "{{ item }}" or ansible_hostname == "{{ item }}"
      with_items: "{{groups['tomcatnodes']}}"

    - debug:
        var: etchostsupdate
