---
- hosts: "localhost"
  connection: local
  become: false
  gather_facts: true  
 
  tasks:
    - name : Execute script
      command: 'ansible -i /etc/ansible/ec2.py tag_Name_tomcat-node* --list'
      register: result 
    - debug:
        var: result

    - name: splitting stdout to make an ansible list of hosts
      set_fact:
        hostlist: result.stdout.split(',')
      register: hostlist 
    - debug:
        var: hostlist

    - name: craeting a list of IP Addresses only from the hostlist variable
      set_fact:
        # ansible_hostname: "{{ hostlist | ipaddr('address')}}"
        ansible_hostname: "{{ hostlist | select('match','^[0-9].*$' ) | list }}"
      register: ansible_hostname
    - debug:
        var: ansible_hostname

    #- name: Update the /etc/hosts file with node name
    #  tags: etchostsupdate
    #  become: yes
    #  become_user: "root"
    #  lineinfile:
    #    path: "/etc/ansible/hosts"
    #    regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
    #    line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
    #    state: present
    #    backup: no
    #  register: etchostsupdate
    #  when: ansible_hostname != "{{ item }}" or ansible_hostname == "{{ item }}"
    #  with_items: "{{groups['tomcatnodes']}}"

    #- debug:
    #  var: etchostsupdate
